### ISSUE TITLE
startHomes not changing?

### ISSUE THREAD

**Issue by dAKirby309** [BlossomMods/BlossomHomes#6]
I keep trying to change the startHomes config code from 2 to 25, or any other number, and nothing happens when I do. I tried changing it on client and server but the number stays at 2. I don't know why.

**Comment by CodedSakura** [comment]
could you check if the /world/data/BlossomHomes.json has the correct value? 

also, what methods specifically did you try and did you restart the server after (or at least use `/blossomlib reload-config`)?

**Comment by dAKirby309** [comment]
Ok I checked /world/data/BlossomHomes.json and yeah, it's set to `"maxHomes": 2` despite changing the config file to 25. But yes, I tried reloading the BlossomLib configs and restarting the server. So I assume manually changing it in world/data should fix that?

**Comment by CodedSakura** [comment]
yea, changing in the /world/data should work, but it also should work with the command or config options...

**Comment by JuceDoesThings** [comment]
I'm having a similar issue! For me, strangely, it seems like one of my users DID have their home limit changed, but the rest did not? Is this because it updates for new joins but doesn't apply the new max to existing players, perhaps?

**Comment by CodedSakura** [comment]
yeah, back when this issue was first created i did not know the issue was that the existing player's homes didn't change, but now that that has happened quite a few times, i do recognize this issue

basically, the `startHomes` config option only applies to new players, which the name somewhat implies.
tho i was pretty sure i had added clarification to the readme that you need to run `/homes set-max <n> @a` to update existing player's max homes
